Repository openshift/kubernetes-autoscaler, pull requests merged in 2019-02, with the labels that each got.

#20 UPSTREAM: <carry> Return error if launch configuration name is missing
  cluster-autoscaler/cloudprovider/aws/aws_manager.go
Labels: lgtm, size/XS

#32 test/openshift/e2e: Smoke test for scale down
  test/openshift/e2e/operator_expectations.go
Labels: lgtm, size/L

#33 UPSTREAM: <carry>: test/openshift/e2e: switch namespace to openshift-machine-api
  test/openshift/e2e/main.go
Labels: lgtm, size/XS

#35 UPSTREAM: <carry>: test/openshift/e2e: handle SIGINT and SIGTERM
  test/openshift/Gopkg.lock
  test/openshift/e2e/main.go
  test/openshift/e2e/operator_expectations.go
  test/openshift/vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/doc.go
  test/openshift/vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/signal.go
  test/openshift/vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/signal_posix.go
  test/openshift/vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/signal_windows.go
Labels: lgtm, size/L

#34 UPSTREAM: <carry>: cloudprovider/openshiftmachineapi: expand unit testing
  cluster-autoscaler/cloudprovider/openshiftmachineapi/export_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_machinedeployment.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_machineset.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_scalableresource.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_utils.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_utils_test.go
Labels: lgtm, size/XXL

#39 UPSTREAM: <carry>: openshift: log nodegroup discovery at level 4
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
Labels: lgtm, size/XS

#36 UPSTREAM: <carry>: openshift: validate nodegroup membership in DeleteNodes()
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Labels: size/L

#42 UPSTREAM: <carry>: openshift: return no nodegroup when scaling size is zero
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Labels: lgtm, size/L
