Repository openshift/kubernetes-autoscaler, pull requests merged in 2019-03, with the labels that each got.

#44 UPSTREAM: <carry>: openshiftmachineapi: remove unused fields
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
Labels: lgtm, size/S

#47 UPSTREAM: <carry>: fix max cluster size calculation on scale up
  cluster-autoscaler/core/scale_up.go
Labels: lgtm, size/XS

#49 UPSTREAM: <carry>: test/openshift/e2e: add Autoscaler focused target
  test/openshift/Makefile
Labels: lgtm, size/S

#50 UPSTREAM: <carry>: openshift: cluster-autoscaler/core: print correct error
  cluster-autoscaler/core/static_autoscaler.go
Labels: lgtm, size/XS

#51 UPSTREAM: <carry>: test/openshift: go get dep if it doesn't exist
  test/openshift/Makefile
Labels: lgtm, size/XS

#52 UPSTREAM: <carry>: test/openshift/Makefile: add rule to bump deps
  test/openshift/Makefile
Labels: lgtm, size/S

#54 UPSTREAM: <carry>: openshift: remove TODO
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
Labels: lgtm, size/XS

#55 UPSTREAM: <carry>: openshift: Rework TestNodeGroupNewNodeGroup
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Labels: lgtm, size/L

#57 UPSTREAM: <carry>: openshift: Rework TestNodeGroupResize
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Labels: lgtm, size/L

#60 UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroups
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
Labels: lgtm, size/L

#56 UPSTREAM: 1745: Allow custom AWS region overrides
  cluster-autoscaler/cloudprovider/aws/aws_manager.go
  cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Labels: lgtm, size/L

#61 UPSTREAM: <carry>: openshift: Rework TestControllerFindMachineByID
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
Labels: lgtm, size/L

#62 UPSTREAM: <carry>: openshift: Rework utils test funcs
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_utils_test.go
Labels: lgtm, size/M

#58 UPSTREAM: <carry>: openshift: Rework TestNodeGroupDeleteNodes
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Labels: lgtm, size/L

#59 UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroupForNodeLookup
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
Labels: lgtm, size/L

#67 UPSTREAM: <carry>: openshift: unit test improvement tidy up
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider_test.go
Labels: lgtm, size/L

#68 UPSTREAM: <carry>: openshift: check for explicit errors
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Labels: lgtm, size/L

#72 UPSTREAM: <carry>: openshift: create git history verification script
  hack/verify_history.sh
Labels: lgtm, size/M

#77 UPSTREAM: <carry>: openshift add unit tests to resize nodegroup
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Labels: lgtm, size/L

#75 UPSTREAM: <carry>: openshift: Add fmt, lint, vet scripts/Makefile
  Makefile
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
Labels: lgtm, size/M
