Repository openshift/kubernetes-autoscaler, pull requests merged in 2019-06, with the labels that each got.

#100 UPSTREAM: <carry>: openshift: prioritise search by Provider ID
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
Labels: lgtm, size/L

#95 Add OpenShift VPA image builds
  vertical-pod-autoscaler/Dockerfile.openshift
  vertical-pod-autoscaler/Dockerfile.rhel7
Labels: lgtm, size/S

#101 Add joelsmith and sjenning to VPA OWNERS file
  vertical-pod-autoscaler/OWNERS
Labels: lgtm, size/XS

#102 UPSTREAM: <carry>: openshift: Move MaxNodesTotalReached event
  cluster-autoscaler/core/scale_up.go
  cluster-autoscaler/core/static_autoscaler.go
Labels: lgtm, size/XS

#103 UPSTREAM: <carry>: openshift: move MaxNodesTotalReached event again
  cluster-autoscaler/core/scale_up.go
Labels: lgtm, size/XS

#106 UPSTREAM: <carry>: openshift: simplify test setup for nodes/replicas
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Labels: lgtm, size/L

#105 UPSTREAM: <carry>: openshift: update criteria for returning a nodegroup
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
Labels: lgtm, size/M

#108 UPSTREAM: <carry>: openshift: Switch builds to use Go 1.12
  cluster-autoscaler.spec
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  images/cluster-autoscaler/Dockerfile
  images/cluster-autoscaler/Dockerfile.rhel7
Labels: lgtm, size/S
