Repository openshift/kubernetes-autoscaler, pull requests merged in 2019-01, with the labels that each got.

#17 UPSTREAM: <carry>: cluster-api: add unit tests for utility functions
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
  cluster-autoscaler/cloudprovider/clusterapi/export_test.go
Labels: lgtm, size/L

#18 UPSTREAM: <carry>: cluster-api: remove obsolete usage of "machine" annotation
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
Labels: lgtm, size/S

#19 UPSTREAM :1425: Report unknown AWS EC2 instance types requested by ASGs
  cluster-autoscaler/cloudprovider/aws/aws_manager.go
Labels: lgtm, size/S

#21 UPSTREAM: <carry>: cluster-api: add unit tests for the machine controller
  cluster-autoscaler/Godeps/Godeps.json
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/fake/doc.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/fake/register.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/doc.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_cluster.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_cluster_client.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_machine.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_machinedeployment.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_machineset.go
Labels: lgtm, size/XXL

#22 Rename ProviderConfig to ProviderSpec
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/common_types.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/defaults.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineclass_types.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
  cluster-autoscaler/vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#28 assign ownership to cloud team
  OWNERS
Labels: lgtm, size/S
