Repository openshift/kubernetes-autoscaler, pull requests merged in 2020-05, with the labels that each got.

#144 BUG 1824215: Raise maximum memory capacity difference
  cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#147 Bug 1823667: UPSTREAM: <carry>: Get replicas always from API server
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset_test.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#150 Bug 1823667: UPSTREAM: <carry>: Compare against minSize in deleteNodes()
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#151 Bug 1835851: Update DeleteNodesTwice test
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#149 Bug 1823667: UPSTREAM: <carry>: Add mutex to DeleteNodes
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
