Repository openshift/kubernetes-autoscaler, pull requests merged in 2020-03, with the labels that each got.

#132 UPSTREAM: <carry>: openshift: enable machineapi_provider_test
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider_test.go
Labels: approved, lgtm, size/XS

#124 Add rphillips to VPA OWNERS file
  vertical-pod-autoscaler/OWNERS
Labels: approved, lgtm, size/XS

#133 UPSTREAM: <carry>: openshift: add the ability to specify clusterapi gvr in env
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
Labels: approved, lgtm, size/L

#136 Add JoelSpeed to Owners
  OWNERS
Labels: approved, lgtm, size/XS

#134 Discover api version
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
Labels: approved, lgtm, size/L

#135 Fix git commit message verification script
  hack/verify_history.sh
Labels: approved, lgtm, size/M

#131 UPSTREAM: 2872: VPA: Update golang.org/x/crypto
  vertical-pod-autoscaler/e2e/go.mod
  vertical-pod-autoscaler/e2e/go.sum
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/blowfish/block.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/blowfish/cipher.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/blowfish/const.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/chacha20/chacha_arm64.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/chacha20/chacha_arm64.s
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/chacha20/chacha_generic.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/chacha20/chacha_noasm.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/chacha20/chacha_s390x.s
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/mac_noasm.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_arm.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_arm.s
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_s390x.s
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/poly1305/sum_vmsl_s390x.s
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/ssh/certs.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/ssh/internal/bcrypt_pbkdf/bcrypt_pbkdf.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/ssh/keys.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/ssh/server.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vertical-pod-autoscaler/e2e/vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vertical-pod-autoscaler/e2e/vendor/modules.txt
  vertical-pod-autoscaler/go.mod
  vertical-pod-autoscaler/go.sum
  vertical-pod-autoscaler/vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vertical-pod-autoscaler/vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vertical-pod-autoscaler/vendor/modules.txt
Labels: approved, lgtm, size/XXL

#138 Remove bison from OWNERS file
  OWNERS
  cluster-autoscaler/OWNERS
Labels: approved, lgtm
