Repository openshift/kubernetes-autoscaler, pull requests merged in 2020-06, with the labels that each got.

#156 UPSTREAM: <carry>: remove redundant error checks in mark/unmark deletion functions
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
Labels: approved, lgtm

#155 Bug 1843039: Add support for rescheduled pods with the same name in drain
  cluster-autoscaler/core/scale_down.go
  cluster-autoscaler/core/scale_down_test.go
  cluster-autoscaler/core/static_autoscaler.go
  cluster-autoscaler/utils/deletetaint/delete.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#152 BUG 1824215: Allow small tolerance on memory capacity when comparing nodegroups
  cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
  cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#153 [release-4.4] BUG 1835160: Fallback to status if replicas nil in spec
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_machinedeployment.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_machineset.go
  cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm
