Repository openshift/kubernetes-autoscaler, pull requests merged in 2020-04, with the labels that each got.

#140 [OCPCLOUD-804] UPSTREAM: 2983: openshift: Provide fake proivder IDs for failed machines
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
  cluster-autoscaler/cloudprovider/clusterapi/machine_types.go
  cluster-autoscaler/cloudprovider/clusterapi/zz_generated.deepcopy.go
Labels: approved, lgtm

#137 UPSTREAM: <carry>: openshift: Implement scale from zero
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters_test.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
Labels: approved, lgtm, size/L

#142 UPSTREAM: 3057: openshift: Do not normalize Node IDs outside of CAPI provider
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
Labels: approved, lgtm

#143 BUG 1820654: UPSTREAM: <carry>: openshift: Fallback to status if replicas nil in spec
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters_test.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
  cluster-autoscaler/cloudprovider/clusterapi/machinedeployment_types.go
  cluster-autoscaler/cloudprovider/clusterapi/machineset_types.go
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#141 BUG 1820410: UPSTREAM: 3034: openshift: Improve delete node mechanisms
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
Labels: approved, bugzilla/valid-bug, lgtm

#146 Bug 1828731: UPSTREAM: <carry>: Convert the mem value consistently with other providers
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm
