Repository openshift/kubernetes-autoscaler, pull requests merged in 2024-01, with the labels that each got.

#275 OCPBUGS-23576: Add Snyk file to exclude vendor directory on scan
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#281 OCPBUGS-27509: Fix unstructured taint parsing in Cluster API provider
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
  cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#283 PODAUTO-104: Add downstream pod autoscaling team member jkyros to VPA OWNERS
  vertical-pod-autoscaler/OWNERS
Labels: approved, lgtm, jira/valid-reference
